### ISSUE TITLE
yoyo in EFF wordlist

### ISSUE THREAD

**Issue by jpnp** [dmuth/diceware#14]
I like the use of the EFF wordlist but it contains both yoyo (66631) and yo-yo (66622).  Depending on only hyphenation to seperate entries seems like a bug (no other hyphenated entry in the EFF list is also present in non-hyphenated form).

Perhaps one of the yoyos can be substituted in your implementation?

**Comment by dmuth** [comment]
Wow, nice find!  I reached out to the author of the EFF wordlist and let them know.

Unless they suggest something differently, I'll probably just replace the hyphenated version with another word in a day or two.

Best,

-- Doug

**Comment by dmuth** [comment]
This has been fixed and uploaded, but I see that it hasn't propagated to https://diceware.dmuth.org/wordlist/wordlist-5-dice-eff.js yet.  Since the site is served through AWS CloudFront, it may be some time for those changes, but the necessary work has been done.

Thanks again for reporting this!

-- Doug
