### ISSUE TITLE
Reduce or eliminate dice animation?

### ISSUE THREAD

**Issue by cbj4074** [dmuth/diceware#15]
Great tool! Thank you for sharing it with the world!

I'd love to see the dice animation time reduced or eliminated entirely because it is (presumably) cosmetic and makes it cumbersome to generate numerous passwords quickly.

I often pick-over several rolls before I find a series of words that I like; I wait until I find words that are memorable for me and don't necessarily just accept the first roll, and I assume others interact with these types of generators similarly.

If a PR is welcome, I'm happy to take a look at the source and see if I can implement the change.

Thanks!

**Comment by dmuth** [comment]
I like this idea!  I originally put the animation in so that non-technical people such as my parents have an idea what's going on.  But I don't think an "expert mode" would hurt, either.

When I get back from vacation next week, I'll look into adding something in.

-- Doug

**Comment by cbj4074** [comment]
Thanks for taking a look, and for your willingness to consider it, Doug!

Another handy feature that you might consider adding to "expert mode" is the ability to generate *n* rolls with a single click, and display them in a simple list format. This would make the tool much more useful for someone who likes to keep rolling until a sufficiently simple and memorable phrase is discovered. The idea is to spare the user having to click repeatedly, perhaps several dozen times, until a "good" phrase results.

**Comment by dmuth** [comment]
Okay, this has been added and should show up on https://diceware.dmuth.org/ shortly.  Here's how to get 4 dice rolls with no animation: https://diceware.dmuth.org/?debug=4&skip_animation

I'm going to hold off on mass production of passwords at this time, because my concern is that users may be more likely to pick and choose a password that they "like", which could have undue influence what password they choose.  But I'm hardly an expert in this area, so if there's any research that you're aware of that explores this angle, please feel free to share with me. (And if not, I think there should be some, because it's an interesting question)

-- Doug
