### ISSUE TITLE
bundle.js missing from /dist/ in repo

### ISSUE THREAD

**Issue by westerness** [dmuth/diceware#25]
It seems that bundle.js is missing from the ./dist/ folder in the repo, which causes the software to be non-functional. Grabbing a copy from your website seems to instantly fix the problem. (My apologies if I'm missing something!) 

PS: Thanks for the awesome software.

**Comment by dmuth** [comment]
Yep, you would need to run `npm build`, which in turn runs `webpack` to create `bundle.js`.

The reason behind that is that `bundle.js` is a single file which contains both my Javascript and that of the libraries it depends on, all in a single file.  And since the code in there isn't unique--it's basically a duplicate of all the source code already in Git, there's no point in checking it into Git. (that, and tweaking a library would cause a new 600 KB `bundle.js` to be created and checked into Git, which would cause the revision log to fill up the with noise..).

Are you having challenges with running `npm` and `webpack`?  I haven't ruled out placing ZIP files of prebuilt releases of Diceware.  If you think that might be helpful, let me know!

-- Doug

**Comment by westerness** [comment]
No, I think I just put my foot in my mouth while also illustrating the perils of reading documentation in the wee hours of the morning. 

To elaborate a bit on my thought process though: 
I took this:

> "Yes. Feel free to clone this repo with git clone https://github.com/dmuth/diceware.git and run it from a local directory on your computer.
> 
> You can also set up a webserver on Mac/Linux boxes by running python3 -m http.server 8000. You will then able to access DiceWare at http://localhost:8000/."
> 
...as being the sum of the instructions if one just wanted to run a copy locally or (say) on an intranet, with the `npm build` stuff being for those who wished to develop/modify the code earlier. I took the comment about running it under an air-gapped environment as confirmation of the same (which is totally on me, to be clear!). I also took that away from the npm build stuff being sub-headers under the 'Development' section of the readme.md. 

Again, none of that is meant to be a complaint or anything, just an explanation of how I arrived at my (mistaken) conclusion. (I figured best-case I'd caught a minor oversight, worst-case I'd look foolish which is no big price to pay.) 

In any case, I'll close this out, and thanks again both for this awesome piece of software and for being so gracious in your reply.

**Comment by dmuth** [comment]
Oh, good find!  Turns out that these instructions are from before I was using webpack, and out of date:

> "Yes. Feel free to clone this repo with git clone https://github.com/dmuth/diceware.git and run it from a local directory on your computer.

I just opened #26 and to track creating a ZIP file release, and updating those instructions accordingly.
